repoUrl: https://github.com/flyotlin/DDS-QoS-Optimization.git
fastddsPath: /home/pdclab/Fast-DDS-python/install/setup.bash
repoPath: /home/pdclab/Optimize-DDS-QoS
config: OMG-Def #
case_num: 1
total_messages: 20000
transport: tcpv4
sending_rate: 1000
controlNodeBasePath: /home/flyotlin/Documents/Program/DDS-QoS-Optimization/
wait_for_timeout: 80
topicPrefix: SimpleStringTopic
host1:
  - p1:t1
  - p2:t2
  - p3:t3
host2:
  - s1:t1
host3:
  - s2:t2
host4:
  - s3:t3
