---
- name: Collect publisher logs
  hosts: publisher
  vars:
    localDest: "/Users/flyotlin/Documents/Program/dds-qos-optimization/case-1/logs/{{ times }}/pub/"
  vars_files:
    - "common_vars.yml"
  tasks:
    - name: Collect
      ansible.builtin.fetch:
        src: "{{ repoDest }}/pub_{{ item }}.log"
        dest: "{{ localDest }}"
        flat: yes
      with_items:
        - "{{ topicName }}_1"
        - "{{ topicName }}_2"
        - "{{ topicName }}_3"

- name: Collect subscriber logs
  hosts: subscriber
  vars:
    localDest: "/Users/flyotlin/Documents/Program/dds-qos-optimization/case-1/logs/{{ times }}/sub/"
  vars_files:
    - "common_vars.yml"
  tasks:
    - name: Collect
      ansible.builtin.fetch:
        src: "{{ repoDest }}/sub_{{ topic }}.log"
        dest: "{{ localDest }}"
        flat: yes
