---
- name: Run Subscriber
  hosts: subscriber
  vars:
    configName: "OMG-Def"
    totalMsgs: 10000
  vars_files:
    - common_vars.yml
  tasks:
    - name: Clone repo
      ansible.builtin.git:
        repo: "{{ repoUrl }}"
        dest: "{{ repoDest }}"
    - name: Generate init-repo script
      template:
        src: init-repo.j2
        dest: "{{ homePath }}/init-repo.sh"
    - name: Initialize repo source code
      command: "bash {{ homePath }}/init-repo.sh"
    - name: Clean old logs
      shell:
        cmd: rm -rf "{{ repoDest }}/*.log"
        executable: /bin/bash
    - name: Run python subscriber script
      shell:
        cmd: |
          source "{{ fastddsSrc }}" && \
          nohup python3 "{{ subscriber }}" --config "{{ configName }}" \
          --messages "{{ totalMsgs }}" \
          --topic "{{ topic }}" &> "{{ repoDest }}/sub_{{ topic }}.log" &
        executable: /bin/bash
